{
 "title": "JH-Main",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "period", "label": "Period [Sec]", "query": "60,300,3600" }
  ]
 },
 "panels": [
  { "title": "AWS ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total network traffic outbound (+) and inbound (-) [bytes/sec]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expression": "SUM(REMOVE_EMPTY(SEARCH('{AWS/EC2,InstanceId} MetricName=\"NetworkIn\"', 'Sum', $period)))/$period",
     "label": "Inbound",
     "metricEditorMode": 1,
     "period": "$period",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Average"
    },
    {
     "expression": "SUM(REMOVE_EMPTY(SEARCH('{AWS/EC2,InstanceId} MetricName=\"NetworkOut\"', 'Sum', $period)))/$period",
     "label": "Outbound",
     "metricEditorMode": 1,
     "period": "$period",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "RDS MySQL - CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "rds-mysql-crypto-dashboard" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Total volumes read (+) and write (-) [bytes/sec]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "dimensions": { "VolumeId": "vol-058625e52b30a152f" },
     "metricName": "VolumeReadBytes",
     "namespace": "AWS/EBS",
     "period": "300",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "VolumeId": "vol-058625e52b30a152f" },
     "metricName": "VolumeWriteBytes",
     "namespace": "AWS/EBS",
     "period": "300",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Total Lambda invocations [count/sec]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expression": "REMOVE_EMPTY(SEARCH('{AWS/Lambda} MetricName=\"Invocations\"', 'Sum', $period))/$period",
     "metricEditorMode": 1,
     "period": "$period",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Lambda invocations per function [count/sec]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expression": "REMOVE_EMPTY(SEARCH('{AWS/Lambda,FunctionName} MetricName=\"Invocations\"', 'Sum', $period))/$period",
     "metricEditorMode": 1,
     "period": "$period",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  { "title": "Github", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Repositories",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "options": { "gitRef": "main", "query": "", "timeField": 1 }, "owner": "jordanholtdev" }
   ]
  },
  {
   "title": "Crypto Dashboard FE Commits",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "options": { "gitRef": "main", "query": "", "timeField": 1 }, "owner": "jordanholtdev", "repository": "crypto-dashboard-frontend" }
   ]
  },
  {
   "title": "Projects FE Commits",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "options": { "gitRef": "main", "query": "", "timeField": 1 }, "owner": "jordanholtdev", "repository": "projects" }
   ]
  },
  {
   "title": "Github Feed FE Commits",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "options": { "gitRef": "main", "query": "", "timeField": 1 }, "owner": "jordanholtdev", "repository": "github-social-feed" }
   ]
  },
  {
   "title": "Projects Pull Requests Created",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "options": { "timeField": 1 },
     "owner": "jordanholtdev",
     "queryMode": "Metrics",
     "region": "default",
     "repository": "projects",
     "statistic": "Average"
    }
   ]
  }
 ]
}