version: '3'
services:
    grafana:
        environment:
            - DEBUG=1
        env_file:
            - .env
        build:
            context: ''
            dockerfile: ./dockerfile.dev
            args:
                - GRAFANA_VERSION=latest
                - GF_INSTALL_PLUGINS=grafana-simple-json-datasource,grafana-github-datasource
                - 'GF_AWS_PROFILES:${AWS_PROFILES}'
                - 'GF_AWS_default_ACCESS_KEY_ID:${AWS_ACCESS_KEY}'
                - 'GF_AWS_default_SECRET_ACCESS_KEY:${AWS_SECRET_KEY}'
                - 'GF_AWS_default_REGION:${AWS_REGION}'
        container_name: grafana
        ports:
            - 3000:3000
        volumes:
            - grafana-data:/var/lib/grafana
volumes:
    grafana-data:
        external: true
