name: Build Docker Container and push to ECR 
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build And Deploy to AWS
    runs-on: ubuntu-latest
    
    steps:
      - name: Amazon ECR "Login" Action for GitHub Actions
      # You may pin to the exact commit or the version.
      # uses: aws-actions/amazon-ecr-login@261a7de32bda11ba01f4d75c4ed6caf3739e54be
        uses: aws-actions/amazon-ecr-login@v1
        with:
          # A comma-delimited list of AWS account IDs that are associated with the ECR Private registries. If you do not specify a registry, the default ECR Private registry is assumed. If 'public' is given as input to 'registry-type', this input is ignored.
          registries: # optional
          # Whether to skip explicit logout of the registries during post-job cleanup. Exists for backward compatibility on self-hosted runners. Not recommended. Options: ['true', 'false']
          skip-logout: # optional, default is false
          # Which ECR registry type to log into. Options: [private, public]
          registry-type: # optional, default is private
